version: '3.8'
volumes:
  data:
  files:

services:
  db:
    build: ./database
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
        - data:/data/db
    ports:
      - 27017:27017
    
  cli:
    build: './cli'
    network_mode: host
    environment:
      user: ${MONGO_ROOT_USER}
      password: ${MONGO_ROOT_PASSWORD}
      auth: admin
    command: tail -F anything
    volumes:
      - files:/data/db
    
    # express:
    #   image: mongo-express
    #   network_mode: host
    #   depends_on:
    #     - db
    #   ports:
    #     - 8081:8081
    #   environment:
    #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
    #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    #     - ME_CONFIG_MONGODB_SERVER=localhost
    #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
    #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}